name: Tests

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  unit:
    runs-on: macos-12.0
    name: Unit tests
    steps: 
      - name: Checkout
        uses: actions/checkout@v3

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_13.4.app && /usr/bin/xcodebuild -version

      - name: Change working directory
        run: cd PokeList

      - name: Run unit tests
        run : xcodebuild test -scheme PokeList -destination "platform=iOS Simulator,OS\=15.5,name\=iPhone 8" | xcpretty

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
